#!/bin/bash

ACTION="$1"

shift

PACKAGE_LIST=$@



case $ACTION in

	preInstall)

		#START openshot-qt
			if [[ " ${PACKAGE_LIST[*]} " == *" openshot-qt "* ]]; then
				echo " * * Start Pre-Installing python3-openshot * * "
				apt update
				apt install python3-openshot -y
				echo " * * Pre-Installed python3-openshot * * "
			fi
		#END openshot-qt
		
	;;	
	
	postInstall)
	
		#START libdvd-package
			if [[ " ${PACKAGE_LIST[*]} " == *" libdvd-pkg "* ]]; then
				echo " * * Start Post-Installing libdvd-pkg * * "
				dpkg-reconfigure -f noninteractive libdvd-pkg
				echo " * * Finished Post-Installing libdvd-pkg * * "
			fi
		#END libdvd-package
			
	;;	

	remove)

		for ix in $PACKAGE_LIST	

		do



			apt-get remove -y $ix

			TEST=$( dpkg-query -s  $ix 2> /dev/null| grep Status | cut -d " " -f 4 )

			if [ "$TEST" == 'installed' ];then

				exit 1

			fi

							

		done		

	;;	

esac

exit 0
